name: CI pour Appli Python

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      # - name: Bundle the application
      #   run: mkdir build && cp static build/static && cd templates build/templates && cd app.py build/app.py && cd requirements.txt build/requirements.txt

      - name: Upload bundle 
        uses: actions/upload-artifact@v4
        with:
          name: cours-cicd-python
          path: | 
            !./.git*
            !./*.md
            .